### ISSUE TITLE
Dockerfile spelling mistake

### ISSUE THREAD

**Issue by mreilaender** [darkounet/opsi-docker#1]
At the definition of the env variable OPSI_USER in line 9, there is a "=" after the variable name which should be without the "=" like so:

ENV OPSI_USER opsi

instead of

ENV OPSI_USER = opsi

Took me 1 hour to realize that ... but it works fine after that litle change
I started the container like so:
    sudo docker run -it --name opsi -h opsi.test.at -p 0.0.0.0:5000:4447 opsi_test /bin/bash

There is 1 thing to mention. You have to specify a hostname for the container because opsi want the server to have a FQDN with at least one dot in it. (see http://download.uib.de/opsi4.0/doc/html/en/opsi-getting-started/opsi-getting-started.html#opsi-getting-started-installation-config-configed -> 2.3)

Thanks to you @darkounet for the great work

**Comment by darkounet** [comment]
thank you @mreilaender 
I will fix this quickly.
Yes we have to force a FQDN hostname for the container if not container doesn't work.

**Comment by darkounet** [comment]
I think this can be close now ;)
